### ISSUE TITLE
CI failing on mypy -- library updated?

### ISSUE THREAD

**Issue by rhoslynroebuck** [IRL2/nanover-protocol#143]
```
python-libraries/nanover-ase/src/nanover/ase/null_calculator.py:12: error: Incompatible types in assignment (expression has type "tuple[str, str]", variable has type "list[str]")  [assignment]
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:57: error: Incompatible types in assignment (expression has type "tuple[str, str, str, str]", variable has type "list[str]")  [assignment]
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:91: error: "MolecularDynamics" has no attribute "temperature"  [attr-defined]
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:94: error: "MolecularDynamics" has no attribute "temp"  [attr-defined]
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:129: error: Incompatible return value type (got "Calculator | None", expected "Calculator")  [return-value]
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:141: error: Incompatible default for argument "atoms" (default has type "None", argument has type "Atoms")  [assignment]
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:141: note: PEP 484 prohibits implicit Optional. Accordingly, mypy has changed its default to no_implicit_optional=True
python-libraries/nanover-ase/src/nanover/ase/imd_calculator.py:141: note: Use https://github.com/hauntsaninja/no_implicit_optional to automatically upgrade your codebase
Found 6 errors in 2 files (checked 69 source files)
Error: Process completed with exit code 1.
```

**Comment by Ragzouken** [comment]
Worked in `3.22.1` but not `3.23.0`?

**Comment by Ragzouken** [comment]
Closed by https://github.com/IRL2/nanover-protocol/pull/144
